/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/opencv.hpp>
#include <android/log.h>
/* Header for class com_wongs_facedetectiontest2_OpencvClass */

using namespace cv;

#ifndef _Included_com_wongs_facedetectiontest2_OpencvClass
#define _Included_com_wongs_facedetectiontest2_OpencvClass
#define LOG_TAG    "hpc -- JNILOG" // 这个是自定义的LOG的标识
#define LOGE(...)  __android_log_print(ANDROID_LOG_ERROR,LOG_TAG, __VA_ARGS__)
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wongs_facedetectiontest2_OpencvClass
 * Method:    faceDetection
 * Signature: (J)V
 */

void detect(Mat& frame);
void detectAndDisplay(Mat frame);

JNIEXPORT void JNICALL Java_com_wongs_facedetectiontest2_OpencvClass_faceDetection
        (JNIEnv *, jclass, jlong);

/*
 * Class:     com_wongs_facedetectiontest2_OpencvClass
 * Method:    nativesTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wongs_facedetectiontest2_OpencvClass_nativesTest
        (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
